from enum import Enum

class FindingType(Enum):
    SYSTEM_TOO_LENIENT = "SYSTEM_TOO_LENIENT"
    CONTROL_WEAKENED = "CONTROL_WEAKENED"
    MISSING_POLICY = "MISSING_POLICY"
    MISSING_SYSTEM = "MISSING_SYSTEM"
    COMPLIANT = "COMPLIANT"
